-- MySQL Script generated by MySQL Workbench
-- Sat Dec  5 12:57:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema newton
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newton` DEFAULT CHARACTER SET utf8 ;
USE `newton` ;

-- -----------------------------------------------------
-- Table `newton`.`m_code_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_code_group` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `name` CHAR(8) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_code` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `name` CHAR(8) NOT NULL COMMENT '',
  `m_code_group_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_m_code_m_code_group_idx` (`m_code_group_id` ASC)  COMMENT '',
  CONSTRAINT `fk_m_code_m_code_group`
    FOREIGN KEY (`m_code_group_id`)
    REFERENCES `newton`.`m_code_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_category` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL DEFAULT 'valid' COMMENT '',
  `category_div` INT NOT NULL COMMENT '',
  `parent_category_id` INT NOT NULL COMMENT '',
  `category_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newton`.`m_faq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_faq` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `content` LONGTEXT NOT NULL COMMENT '',
  `talk_script` LONGTEXT NULL DEFAULT NULL COMMENT '',
  `useful_count` INT(11) NULL DEFAULT NULL COMMENT '',
  `m_faq_category_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_m_faq_m_faq_category1_idx` (`m_faq_category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_m_faq_m_faq_category1`
    FOREIGN KEY (`m_faq_category_id`)
    REFERENCES `newton`.`m_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_manual_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_manual_category` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_manual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_manual` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `file_name` VARCHAR(255) NOT NULL COMMENT '',
  `file_path` VARCHAR(255) NOT NULL COMMENT '',
  `m_manual_category_id` INT NOT NULL COMMENT '',
  `m_category_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_m_manual_file_m_category1_idx` (`m_category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_m_manual_file_m_category1`
    FOREIGN KEY (`m_category_id`)
    REFERENCES `newton`.`m_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_manual_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_manual_list` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `m_manual_category_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_m_manual_list_m_manual_category1_idx` (`m_manual_category_id` ASC)  COMMENT '',
  CONSTRAINT `fk_m_manual_list_m_manual_category1`
    FOREIGN KEY (`m_manual_category_id`)
    REFERENCES `newton`.`m_manual_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_notification` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL DEFAULT 'valid' COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `content` LONGTEXT NULL DEFAULT NULL COMMENT '',
  `file_path` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `importance` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_notification_target_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_notification_target_role` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `target_user` CHAR(8) NOT NULL COMMENT '',
  `read_flag` BIT(1) NOT NULL DEFAULT b'0' COMMENT '',
  `m_notification_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_m_notification_target_role_m_notification1_idx` (`m_notification_id` ASC)  COMMENT '',
  CONSTRAINT `fk_m_notification_target_role_m_notification1`
    FOREIGN KEY (`m_notification_id`)
    REFERENCES `newton`.`m_notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_role` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '\n	',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `skill` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '\n',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '	\n',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_user_has_m_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_user_has_m_role` (
  `m_user_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  `m_role_id` INT(10) UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`m_user_id`, `m_role_id`)  COMMENT '',
  INDEX `fk_m_user_has_m_role_m_role1_idx` (`m_role_id` ASC)  COMMENT '',
  INDEX `fk_m_user_has_m_role_m_user1_idx` (`m_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_m_user_has_m_role_m_role1`
    FOREIGN KEY (`m_role_id`)
    REFERENCES `newton`.`m_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_m_user_has_m_role_m_user1`
    FOREIGN KEY (`m_user_id`)
    REFERENCES `newton`.`m_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `newton`.`m_white_board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newton`.`m_white_board` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `create_user` CHAR(8) NOT NULL COMMENT '',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  `update_user` CHAR(8) NOT NULL COMMENT '',
  `status` CHAR(8) NOT NULL DEFAULT 'valid' COMMENT '',
  `content` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
